create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text,
  status text not null default 'owned' check (status in ('owned','read','wishlist','selling')),
  genre text,
  notes text,
  price numeric(10,2),
  cover_url text,
  created_at timestamptz not null default now()
);

alter table public.books enable row level security;

drop policy if exists "books public read" on public.books;
drop policy if exists "books public insert" on public.books;
drop policy if exists "books public update" on public.books;
drop policy if exists "books public delete" on public.books;

create policy "books public read" on public.books for select using (true);
create policy "books public insert" on public.books for insert with check (true);
create policy "books public update" on public.books for update using (true) with check (true);
create policy "books public delete" on public.books for delete using (true);
