-- MINHA BIBLIOTECA
-- Execute este arquivo no SQL Editor do seu projeto Supabase.

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text,
  status text not null default 'owned' check (status in ('owned', 'read', 'wishlist', 'selling')),
  genre text,
  price numeric(10,2),
  cover_url text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists books_status_idx on public.books(status);
create index if not exists books_title_idx on public.books(title);

alter table public.books enable row level security;

drop policy if exists "books_select" on public.books;
drop policy if exists "books_insert" on public.books;
drop policy if exists "books_update" on public.books;
drop policy if exists "books_delete" on public.books;

-- Para a primeira versão da aplicação, o acesso é permitido pelo frontend.
-- Quando o login de usuários for adicionado, estas políticas deverão ser
-- substituídas por políticas vinculadas a auth.uid().
create policy "books_select" on public.books for select using (true);
create policy "books_insert" on public.books for insert with check (true);
create policy "books_update" on public.books for update using (true) with check (true);
create policy "books_delete" on public.books for delete using (true);

create or replace function public.set_books_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists books_updated_at on public.books;
create trigger books_updated_at
before update on public.books
for each row execute function public.set_books_updated_at();
